//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokoBeDia.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TokoBeDiaEntities : DbContext
    {
        public TokoBeDiaEntities()
            : base("name=TokoBeDiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MsProduct> MsProducts { get; set; }
        public virtual DbSet<MsProductType> MsProductTypes { get; set; }
        public virtual DbSet<MsRole> MsRoles { get; set; }
        public virtual DbSet<MsUser> MsUsers { get; set; }
        public virtual DbSet<TrDetailTransaction> TrDetailTransactions { get; set; }
        public virtual DbSet<TrHeaderTransaction> TrHeaderTransactions { get; set; }
    }
}
